const mockData = [
  {
    id: 26,
    host: "GitHub",
    login: "taubyte",
    name: "Taubyte",
    uuid: "120687264",
    kind: "organization",
    description:
      "Infrastructure's Autopilot - Local Coding Equals Global Production",
    email: null,
    website: "taubyte.com",
    location: null,
    twitter: null,
    company: null,
    icon_url: "https://avatars.githubusercontent.com/u/120687264?v=4",
    repositories_count: 42,
    last_synced_at: "2024-04-03T09:00:11.628Z",
    html_url: "https://github.com/taubyte",
    total_stars: 293,
    dependent_repos_count: 8,
    followers: 47,
    following: 0,
    created_at: "2023-02-14T20:09:22.048Z",
    updated_at: "2024-04-01T15:05:46.330Z",
    maintainers: [],
  },
  {
    id: 66,
    host: "GitHub",
    login: "streamingfast",
    name: "StreamingFast",
    uuid: "77980295",
    kind: "organization",
    description:
      "StreamingFast is a protocol infrastructure company that provides a massively scalable architecture for streaming blockchain data",
    email: null,
    website: "https://streamingfast.io",
    location: null,
    twitter: "streamingfastio",
    company: null,
    icon_url: "https://avatars.githubusercontent.com/u/77980295?v=4",
    repositories_count: 97,
    last_synced_at: "2024-04-03T09:00:18.764Z",
    html_url: "https://github.com/streamingfast",
    total_stars: null,
    dependent_repos_count: 6,
    followers: null,
    following: null,
    created_at: "2022-11-14T08:30:38.564Z",
    updated_at: "2024-04-03T09:00:18.765Z",
    maintainers: ["maoueh"],
  },
  {
    id: 277,
    host: "GitHub",
    login: "0xPolygonID",
    name: "Polygon ID",
    uuid: "101261660",
    kind: "organization",
    description: "A self-sovereign private identity solution",
    email: null,
    website: "https://polygonid.com",
    location: null,
    twitter: "0xPolygonID",
    company: null,
    icon_url: "https://avatars.githubusercontent.com/u/101261660?v=4",
    repositories_count: 31,
    last_synced_at: "2024-04-03T14:00:33.259Z",
    html_url: "https://github.com/0xPolygonID",
    total_stars: 380,
    dependent_repos_count: 5,
    followers: 247,
    following: 0,
    created_at: "2023-02-20T05:05:45.527Z",
    updated_at: "2024-04-01T16:05:32.152Z",
    maintainers: ["Kolezhniuk", "vmidyllic", "volodymyr-basiuk"],
  },
  {
    id: 152,
    host: "GitHub",
    login: "glifio",
    name: "Glif",
    uuid: "72399488",
    kind: "organization",
    description: "Interoperable tools for the Filecoin network",
    email: null,
    website: "glif.io",
    location: null,
    twitter: null,
    company: null,
    icon_url: "https://avatars.githubusercontent.com/u/72399488?v=4",
    repositories_count: 65,
    last_synced_at: "2024-04-03T10:00:12.404Z",
    html_url: "https://github.com/glifio",
    total_stars: 283,
    dependent_repos_count: 5,
    followers: 38,
    following: 0,
    created_at: "2022-11-14T05:07:31.170Z",
    updated_at: "2024-04-01T15:24:44.416Z",
    maintainers: ["jimpick"],
  },
  {
    id: 63,
    host: "GitHub",
    login: "singulargarden",
    name: "SingularGarden",
    uuid: "29306246",
    kind: "organization",
    description:
      "We grow great projects.  Web Apps, Distributed Systems, and Decentralized Systems.",
    email: "github@singulargarden.com",
    website: "https://www.singulargarden.com",
    location: null,
    twitter: "singulargarden",
    company: null,
    icon_url: "https://avatars.githubusercontent.com/u/29306246?v=4",
    repositories_count: 12,
    last_synced_at: "2024-04-03T09:00:18.481Z",
    html_url: "https://github.com/singulargarden",
    total_stars: 2,
    dependent_repos_count: 5,
    followers: 6,
    following: 0,
    created_at: "2022-11-17T09:20:21.326Z",
    updated_at: "2024-04-01T15:09:20.332Z",
    maintainers: [],
  },
  {
    id: 357,
    host: "GitHub",
    login: "filecoin-project",
    name: "Filecoin",
    uuid: "22014611",
    kind: "organization",
    description: "",
    email: null,
    website: "https://filecoin.io",
    location: null,
    twitter: null,
    company: null,
    icon_url: "https://avatars.githubusercontent.com/u/22014611?v=4",
    repositories_count: 177,
    last_synced_at: "2024-04-03T16:00:10.762Z",
    html_url: "https://github.com/filecoin-project",
    total_stars: null,
    dependent_repos_count: 4,
    followers: null,
    following: null,
    created_at: "2022-11-13T06:10:38.523Z",
    updated_at: "2023-03-02T14:25:17.319Z",
    maintainers: [
      "Stebalien",
      "anorth",
      "alexytsu",
      "Terryhung",
      "rvagg",
      "Fatman13",
      "simlecode",
      "hannahhoward",
      "LinZexiao",
      "ranchalp",
      "matejpavlovic",
      "jennijuju",
      "LexLuthr",
      "jacobheun",
      "cryptonemo",
      "dirkmc",
      "elvin-du",
      "diwufeiwen",
      "willscott",
      "birdychang",
      "vmx",
      "raulk",
      "web3-bot",
      "nonsense",
      "hunjixin",
      "masih",
      "YiRuiLiher",
      "magik6k",
      "maciejwitowski",
      "0x5459",
      "longfeiWan9",
      "LaurenSpiegel",
      "kylehuntsman",
      "kasteph",
      "Joss-Hua",
      "ianconsolata",
      "DiegoRBaquero",
      "davidd8",
      "cxytz01",
      "cwaring",
      "brendalee",
      "BlocksOnAChain",
    ],
  },
  {
    id: 419,
    host: "GitHub",
    login: "masa-finance",
    name: "Masa Finance",
    uuid: "80600478",
    kind: "organization",
    description:
      "🌽 Masa, the premiere web3 identity and credit protocol. Be the first to build soulbound tokens in web3.",
    email: "help@masa.finance",
    website: "https://masa.finance",
    location: null,
    twitter: "getmasafi",
    company: null,
    icon_url: "https://avatars.githubusercontent.com/u/80600478?v=4",
    repositories_count: 7,
    last_synced_at: "2024-04-03T07:00:33.740Z",
    html_url: "https://github.com/masa-finance",
    total_stars: null,
    dependent_repos_count: 3,
    followers: null,
    following: null,
    created_at: "2022-11-16T04:43:47.628Z",
    updated_at: "2023-03-06T04:29:14.934Z",
    maintainers: [],
  },
];

export default mockData;
